version: 2
updates:
  - package-ecosystem: gomod
    directory: /sitemap-dupes
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /sitemap-validator
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
